// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqYeOSehB0BSf-M3qK898nzEXLCWpLUdA',
    appId: '1:664648104830:web:284205253c6d4f36cfd12f',
    messagingSenderId: '664648104830',
    projectId: 'learnit-568ce',
    authDomain: 'learnit-568ce.firebaseapp.com',
    storageBucket: 'learnit-568ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2VpwR97V1qzlXFSSaY2U3_Oq8Nthzm0',
    appId: '1:664648104830:android:1531ba7586ee832bcfd12f',
    messagingSenderId: '664648104830',
    projectId: 'learnit-568ce',
    storageBucket: 'learnit-568ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw7jjHYOoFeb0Zm3hMP32FPVFp0S_8HRY',
    appId: '1:664648104830:ios:3f84cb45d0b519e3cfd12f',
    messagingSenderId: '664648104830',
    projectId: 'learnit-568ce',
    storageBucket: 'learnit-568ce.appspot.com',
    iosBundleId: 'de.mwa.learnit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw7jjHYOoFeb0Zm3hMP32FPVFp0S_8HRY',
    appId: '1:664648104830:ios:3f84cb45d0b519e3cfd12f',
    messagingSenderId: '664648104830',
    projectId: 'learnit-568ce',
    storageBucket: 'learnit-568ce.appspot.com',
    iosBundleId: 'de.mwa.learnit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqYeOSehB0BSf-M3qK898nzEXLCWpLUdA',
    appId: '1:664648104830:web:770446817ab985f8cfd12f',
    messagingSenderId: '664648104830',
    projectId: 'learnit-568ce',
    authDomain: 'learnit-568ce.firebaseapp.com',
    storageBucket: 'learnit-568ce.appspot.com',
  );
}
